// <auto-generated />
using System;
using APIpayApplication.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIpayApplication.Migrations
{
    [DbContext(typeof(PayContext))]
    [Migration("20200614031056_secondMigration")]
    partial class secondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APIpayApplication.Models.Card", b =>
                {
                    b.Property<string>("IdCard")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("CardNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateModify")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IdUser")
                        .HasColumnType("text");

                    b.HasKey("IdCard");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("APIpayApplication.Models.Expense", b =>
                {
                    b.Property<string>("IdExpense")
                        .HasColumnType("varchar(767)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DateApply")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IdCard")
                        .HasColumnType("text");

                    b.Property<string>("IdUser")
                        .HasColumnType("text");

                    b.HasKey("IdExpense");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("APIpayApplication.Models.Income", b =>
                {
                    b.Property<string>("IdIncome")
                        .HasColumnType("varchar(767)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DateApply")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IdCard")
                        .HasColumnType("text");

                    b.Property<string>("IdMoneda")
                        .HasColumnType("text");

                    b.Property<string>("IdUser")
                        .HasColumnType("text");

                    b.HasKey("IdIncome");

                    b.ToTable("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
